# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pcminfo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pcminfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpcminfo.proto\x12\x0bproject_api\"3\n\x11ProjectIdentifier\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x10\n\x08\x63ustomer\x18\x02 \x01(\t\"L\n\x15ProjectIdentifierList\x12\x33\n\x0bidentifiers\x18\x01 \x03(\x0b\x32\x1e.project_api.ProjectIdentifier\"\xd9\x04\n\x0eProjectProfile\x12\x10\n\x08\x63ustomer\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x15\n\rab_generation\x18\x03 \x01(\t\x12\x0b\n\x03sop\x18\x04 \x01(\x05\x12\x17\n\x0fvehicle_variant\x18\x05 \x01(\t\x12\x11\n\tplattform\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\x12\x18\n\x10vint_responsible\x18\x08 \x01(\t\x12\x16\n\x0eproject_leader\x18\t \x01(\t\x12\x0e\n\x06region\x18\n \x01(\t\x12\x0b\n\x03oem\x18\x0b \x01(\t\x12\r\n\x05model\x18\x0c \x01(\t\x12\'\n\x1fperipheral_sensor_configuration\x18\r \x01(\t\x12%\n\x1dinternal_sensor_configuration\x18\x0e \x01(\t\x12\x14\n\x0crole_summary\x18\x0f \x01(\t\x12\x14\n\x0c\x44igit10OemPn\x18\x10 \x01(\t\x12\x15\n\rcustomerOemPn\x18\x11 \x01(\t\x12\x17\n\x0f\x46lConfiguration\x18\x12 \x01(\t\x12\x14\n\x0cTargetMarket\x18\x13 \x01(\t\x12\x0e\n\x06MCR_No\x18\x14 \x01(\t\x12\x1a\n\x12\x43onnectorDirection\x18\x15 \x01(\t\x12\x0e\n\x06Status\x18\x16 \x01(\t\x12\x16\n\x0e\x41lmProjectName\x18\x17 \x01(\t\x12\x1a\n\x12ReferenceProjectPn\x18\x18 \x01(\t\x12\x1a\n\x12ReferenceProjectBm\x18\x19 \x01(\t\x12\x1a\n\x12role_email_summary\x18\x1a \x01(\t\"C\n\x12ProjectProfileList\x12-\n\x08profiles\x18\x01 \x03(\x0b\x32\x1b.project_api.ProjectProfileb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pcminfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROJECTIDENTIFIER']._serialized_start=30
  _globals['_PROJECTIDENTIFIER']._serialized_end=81
  _globals['_PROJECTIDENTIFIERLIST']._serialized_start=83
  _globals['_PROJECTIDENTIFIERLIST']._serialized_end=159
  _globals['_PROJECTPROFILE']._serialized_start=162
  _globals['_PROJECTPROFILE']._serialized_end=763
  _globals['_PROJECTPROFILELIST']._serialized_start=765
  _globals['_PROJECTPROFILELIST']._serialized_end=832
# @@protoc_insertion_point(module_scope)
