# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dataprovider_pb2 as dataprovider__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dataprovider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataProviderStub(object):
    """==========================================================
    服务定义 (Service Definition)
    ==========================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProjectIdentifiers = channel.unary_unary(
                '/dataprovider.DataProvider/GetProjectIdentifiers',
                request_serializer=dataprovider__pb2.GetIdentifiersRequest.SerializeToString,
                response_deserializer=dataprovider__pb2.ProjectIdentifierList.FromString,
                _registered_method=True)
        self.GetProjectInformationByUuid = channel.unary_unary(
                '/dataprovider.DataProvider/GetProjectInformationByUuid',
                request_serializer=dataprovider__pb2.GetInformationByUuidRequest.SerializeToString,
                response_deserializer=dataprovider__pb2.ProjectProfile.FromString,
                _registered_method=True)
        self.StreamAllProjectDetails = channel.unary_stream(
                '/dataprovider.DataProvider/StreamAllProjectDetails',
                request_serializer=dataprovider__pb2.GetIdentifiersRequest.SerializeToString,
                response_deserializer=dataprovider__pb2.ProjectProfile.FromString,
                _registered_method=True)


class DataProviderServicer(object):
    """==========================================================
    服务定义 (Service Definition)
    ==========================================================
    """

    def GetProjectIdentifiers(self, request, context):
        """对应原 /api/v1/identifiers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectInformationByUuid(self, request, context):
        """对应原 /api/v1/projects/info/{uuid}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAllProjectDetails(self, request, context):
        """(新增) 一个服务端流式RPC，一次性获取所有项目的详细信息
        这比多次调用 GetProjectInformationByUuid 效率高得多
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProjectIdentifiers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectIdentifiers,
                    request_deserializer=dataprovider__pb2.GetIdentifiersRequest.FromString,
                    response_serializer=dataprovider__pb2.ProjectIdentifierList.SerializeToString,
            ),
            'GetProjectInformationByUuid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectInformationByUuid,
                    request_deserializer=dataprovider__pb2.GetInformationByUuidRequest.FromString,
                    response_serializer=dataprovider__pb2.ProjectProfile.SerializeToString,
            ),
            'StreamAllProjectDetails': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAllProjectDetails,
                    request_deserializer=dataprovider__pb2.GetIdentifiersRequest.FromString,
                    response_serializer=dataprovider__pb2.ProjectProfile.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataprovider.DataProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataprovider.DataProvider', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataProvider(object):
    """==========================================================
    服务定义 (Service Definition)
    ==========================================================
    """

    @staticmethod
    def GetProjectIdentifiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataprovider.DataProvider/GetProjectIdentifiers',
            dataprovider__pb2.GetIdentifiersRequest.SerializeToString,
            dataprovider__pb2.ProjectIdentifierList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectInformationByUuid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataprovider.DataProvider/GetProjectInformationByUuid',
            dataprovider__pb2.GetInformationByUuidRequest.SerializeToString,
            dataprovider__pb2.ProjectProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamAllProjectDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/dataprovider.DataProvider/StreamAllProjectDetails',
            dataprovider__pb2.GetIdentifiersRequest.SerializeToString,
            dataprovider__pb2.ProjectProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
