# =========================
# Base image
# =========================
FROM python:3.12-slim

# =========================
# Environment
# =========================
ENV PYTHONUNBUFFERED=1

# =========================
# Working directory
# =========================
WORKDIR /app-puma

# =========================
# Pip index (private registry)
# =========================
ARG PIP_INDEX_URL=https://anu9rng:AP6eY5xuhS1MqAdy5jedftw3ndQq7MHjXL8Rpb@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
ENV PIP_INDEX_URL=${PIP_INDEX_URL}

# =========================
# Install dependencies
# =========================
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# =========================
# Copy application code
# =========================
COPY . .

# =========================
# Expose port
# =========================
EXPOSE 8086

# =========================
# Start command
# =========================
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8086"]
